### ISSUE TITLE
no WEAK support (as advertised)

### ISSUE THREAD

**Issue by wodz** [PeterMcKinnis/WostCaseStack#1]
README states no WEAK defined functions are supported, granted. What is the problem with this? This limitation makes it impossible to use this tool in order to analyze most of embedded software as usually startup code defines default IRQ handlers as WEAK.

**Comment by saeugetier** [comment]
I'm using this analyzer with STM32 HAL. The HAL uses weak declarations. Will there be a fix that the 
analyzer can deal with weak functions?`

Currently WCS throws an exception:
Exception: Error Unknown Binding "WEAK" for symbol: HAL_MspInit

**Comment by PeterMcKinnis** [comment]
I have had others ask this as well.  I will look into it.  Are you able to
share the project you are compiling?

Regards
Peter

**Comment by PeterMcKinnis** [comment]
Closing for now.  Will consider adding WEAK support if someone can send an example project to test with.
